// Banderas reales (no emoji) a partir del nombre del equipo.
// Las cuotas llegan con label tipo "Ecuador vs. Senegal"; de ahí
// derivamos los dos equipos y su bandera vía flagcdn.com.
// Si un equipo no está en el mapa, devolvemos null y la UI muestra
// un marcador neutro en lugar de una bandera rota.

const FLAG_CODES: Record<string, string> = {
  Afganistán: 'af',
  Albania: 'al',
  Alemania: 'de',
  Andorra: 'ad',
  Angola: 'ao',
  'Antigua y Barbuda': 'ag',
  'Arabia Saudita': 'sa',
  Argelia: 'dz',
  Argentina: 'ar',
  Armenia: 'am',
  Australia: 'au',
  Austria: 'at',
  Azerbaiyán: 'az',
  Bahamas: 'bs',
  Bangladés: 'bd',
  Barbados: 'bb',
  Baréin: 'bh',
  Bélgica: 'be',
  Belice: 'bz',
  Benín: 'bj',
  Bielorrusia: 'by',
  Bolivia: 'bo',
  'Bosnia y Herzegovina': 'ba',
  Botsuana: 'bw',
  Brasil: 'br',
  Brunéi: 'bn',
  Bulgaria: 'bg',
  'Burkina Faso': 'bf',
  Burundi: 'bi',
  Bután: 'bt',
  'Cabo Verde': 'cv',
  Camboya: 'kh',
  Camerún: 'cm',
  Canadá: 'ca',
  Catar: 'qa',
  Chad: 'td',
  Chile: 'cl',
  China: 'cn',
  Chipre: 'cy',
  Colombia: 'co',
  Comoras: 'km',
  'Corea del Norte': 'kp',
  'Corea del Sur': 'kr',
  'Costa de Marfil': 'ci',
  'Costa Rica': 'cr',
  Croacia: 'hr',
  Cuba: 'cu',
  Dinamarca: 'dk',
  Dominica: 'dm',
  Ecuador: 'ec',
  Egipto: 'eg',
  'El Salvador': 'sv',
  'Emiratos Árabes Unidos': 'ae',
  Eritrea: 'er',
  Escocia: 'gb-sct',
  Eslovaquia: 'sk',
  Eslovenia: 'si',
  España: 'es',
  'Estados Unidos': 'us',
  Estonia: 'ee',
  Esuatini: 'sz',
  Etiopía: 'et',
  Filipinas: 'ph',
  Finlandia: 'fi',
  Fiyi: 'fj',
  Francia: 'fr',
  Gabón: 'ga',
  Gales: 'gb-wls',
  Gambia: 'gm',
  Georgia: 'ge',
  Ghana: 'gh',
  Granada: 'gd',
  Grecia: 'gr',
  Guatemala: 'gt',
  Guinea: 'gn',
  'Guinea-Bisáu': 'gw',
  'Guinea Ecuatorial': 'gq',
  Guyana: 'gy',
  Haití: 'ht',
  Honduras: 'hn',
  Hungría: 'hu',
  India: 'in',
  Indonesia: 'id',
  Inglaterra: 'gb-eng',
  Irak: 'iq',
  Irán: 'ir',
  Irlanda: 'ie',
  'Irlanda del Norte': 'gb-nir',
  Islandia: 'is',
  'Islas Marshall': 'mh',
  'Islas Salomón': 'sb',
  Israel: 'il',
  Italia: 'it',
  Jamaica: 'jm',
  Japón: 'jp',
  Jordania: 'jo',
  Kazajistán: 'kz',
  Kenia: 'ke',
  Kirguistán: 'kg',
  Kiribati: 'ki',
  Kosovo: 'xk',
  Kuwait: 'kw',
  Laos: 'la',
  Lesoto: 'ls',
  Letonia: 'lv',
  Líbano: 'lb',
  Liberia: 'lr',
  Libia: 'ly',
  Liechtenstein: 'li',
  Lituania: 'lt',
  Luxemburgo: 'lu',
  Macedonia: 'mk',
  Madagascar: 'mg',
  Malasia: 'my',
  Malaui: 'mw',
  Maldivas: 'mv',
  Malí: 'ml',
  Malta: 'mt',
  Marruecos: 'ma',
  Mauricio: 'mu',
  Mauritania: 'mr',
  México: 'mx',
  Micronesia: 'fm',
  Moldavia: 'md',
  Mónaco: 'mc',
  Mongolia: 'mn',
  Montenegro: 'me',
  Mozambique: 'mz',
  Myanmar: 'mm',
  Namibia: 'na',
  Nauru: 'nr',
  Nepal: 'np',
  Nicaragua: 'ni',
  Níger: 'ne',
  Nigeria: 'ng',
  Noruega: 'no',
  'Nueva Zelanda': 'nz',
  Omán: 'om',
  'Países Bajos': 'nl',
  Pakistán: 'pk',
  Palaos: 'pw',
  Palestina: 'ps',
  Panamá: 'pa',
  'Papúa Nueva Guinea': 'pg',
  Paraguay: 'py',
  Perú: 'pe',
  Polonia: 'pl',
  Portugal: 'pt',
  'Reino Unido': 'gb',
  'República Centroafricana': 'cf',
  'República Checa': 'cz',
  'República Democrática del Congo': 'cd',
  'República del Congo': 'cg',
  'República Dominicana': 'do',
  Ruanda: 'rw',
  Rumania: 'ro',
  Rusia: 'ru',
  Samoa: 'ws',
  'San Cristóbal y Nieves': 'kn',
  'San Marino': 'sm',
  'San Vicente y las Granadinas': 'vc',
  'Santa Lucía': 'lc',
  'Santo Tomé y Príncipe': 'st',
  Senegal: 'sn',
  Serbia: 'rs',
  Seychelles: 'sc',
  'Sierra Leona': 'sl',
  Singapur: 'sg',
  Siria: 'sy',
  Somalia: 'so',
  'Sri Lanka': 'lk',
  Sudáfrica: 'za',
  Sudán: 'sd',
  'Sudán del Sur': 'ss',
  Suecia: 'se',
  Suiza: 'ch',
  Surinam: 'sr',
  Tailandia: 'th',
  Taiwán: 'tw',
  Tanzania: 'tz',
  Tayikistán: 'tj',
  'Timor Oriental': 'tl',
  Togo: 'tg',
  Tonga: 'to',
  'Trinidad y Tobago': 'tt',
  Túnez: 'tn',
  Turkmenistán: 'tm',
  Turquía: 'tr',
  Tuvalu: 'tv',
  Ucrania: 'ua',
  Uganda: 'ug',
  Uruguay: 'uy',
  Uzbekistán: 'uz',
  Vanuatu: 'vu',
  Vaticano: 'va',
  Venezuela: 've',
  Vietnam: 'vn',
  Yemen: 'ye',
  Yibuti: 'dj',
  Zambia: 'zm',
  Zimbabue: 'zw'
}

/** Devuelve la URL SVG de la bandera, o null si no se conoce el equipo. */
export function flagUrl(team: string): string | null {
  const code = FLAG_CODES[team.trim()]
  return code ? `https://flagcdn.com/${code}.svg` : null
}

/** "Ecuador vs. Senegal" -> ["Ecuador", "Senegal"] (o null si no se puede dividir). */
export function teamsFromLabel(label: string): [string, string] | null {
  const parts = label.split(/\s+vs\.?\s+/i)
  if (parts.length === 2) return [parts[0].trim(), parts[1].trim()]
  return null
}

/** Etiqueta corta y alineable para cada resultado: 1 / X / 2. */
export function outcomeSymbol(code: 'home' | 'draw' | 'away'): string {
  return code === 'home' ? '1' : code === 'draw' ? 'X' : '2'
}
